# Generated by Django 5.2.13 on 2026-05-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_courseregistration_id_alter_student_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseRegistration",
        ),
    ]
