# Generated by Django 5.2.13 on 2026-05-08 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_courseoutline"),
        ("core", "0003_alter_semester_options_alter_session_options_and_more"),
        ("students", "0003_delete_courseregistration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["-date_enrolled"]},
        ),
        migrations.CreateModel(
            name="CourseRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_registered", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.semester"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Registration",
                "verbose_name_plural": "Course Registrations",
            },
        ),
        migrations.CreateModel(
            name="CourseRegistrationDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.course",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.courseregistration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registered Course",
                "verbose_name_plural": "Registered Courses",
                "unique_together": {("registration", "course")},
            },
        ),
        migrations.AddField(
            model_name="courseregistration",
            name="courses",
            field=models.ManyToManyField(
                through="students.CourseRegistrationDetail", to="academics.course"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseregistration",
            unique_together={("student", "semester")},
        ),
    ]
