# Generated by Django 5.2.13 on 2026-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_student_options_courseregistration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="entry_mode",
            field=models.CharField(blank=True, default="O-LEVEL", max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "MALE"), ("F", "FEMALE")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="state_of_origin",
            field=models.CharField(blank=True, default="KATSINA", max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="year_admitted",
            field=models.CharField(blank=True, default="", max_length=9),
        ),
    ]
