# Generated by Django 5.2.13 on 2026-07-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_student_date_of_birth_student_entry_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="must_change_password",
            field=models.BooleanField(default=True),
        ),
    ]
