# Generated by Django 5.2.13 on 2026-05-06 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_semester_id_alter_session_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="semester",
            options={"ordering": ["session", "name"]},
        ),
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["-name"]},
        ),
        migrations.AddField(
            model_name="semester",
            name="reg_open",
            field=models.BooleanField(
                default=False, verbose_name="Course Registration Open"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="semester",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="semester",
            name="name",
            field=models.CharField(
                choices=[
                    ("First Semester", "First Semester"),
                    ("Second Semester", "Second Semester"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("session", "name")},
        ),
    ]
