# Generated by Django 5.1.3 on 2026-05-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_semester_options_alter_session_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="accepts_applications",
            field=models.BooleanField(default=False),
        ),
    ]
