# Generated by Django 5.1.3 on 2026-05-18 21:57

import admissions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0004_courseoutline"),
        ("core", "0003_alter_semester_options_alter_session_options_and_more"),
        ("students", "0005_student_date_of_birth_student_entry_mode_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_number",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending App Fee Payment"),
                            ("app_fee_submitted", "App Fee Submitted"),
                            ("app_fee_confirmed", "App Fee Confirmed"),
                            ("admitted", "Admitted - Awaiting School Fee"),
                            ("school_fee_submitted", "School Fee Submitted"),
                            (
                                "school_fee_approved",
                                "School Fee Approved - Matric Assigned",
                            ),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("nationality", models.CharField(default="Nigerian", max_length=80)),
                ("state_of_origin", models.CharField(max_length=80)),
                ("lga", models.CharField(max_length=80)),
                ("religion", models.CharField(blank=True, max_length=50)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=admissions.models.application_photo_path,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("app_fee_reference", models.CharField(blank=True, max_length=100)),
                ("app_fee_date", models.DateField(blank=True, null=True)),
                ("app_fee_bank", models.CharField(blank=True, max_length=100)),
                ("app_fee_confirmed", models.BooleanField(default=False)),
                ("admission_date", models.DateTimeField(blank=True, null=True)),
                ("matric_number", models.CharField(blank=True, max_length=30)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "admitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admitted_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "app_fee_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_app_fees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.programme",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.session",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OLevelResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("WAEC", "WAEC"),
                            ("NECO", "NECO"),
                            ("NABTEB", "NABTEB"),
                        ],
                        max_length=10,
                    ),
                ),
                ("exam_year", models.CharField(max_length=4)),
                ("exam_number", models.CharField(max_length=30)),
                (
                    "sitting",
                    models.CharField(
                        choices=[("1st", "1st Sitting"), ("2nd", "2nd Sitting")],
                        default="1st",
                        max_length=10,
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="olevel",
                        to="admissions.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolFeeInvoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=25000, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Invoice Generated"),
                            ("submitted", "Payment Submitted"),
                            ("approved", "Approved - Matric Assigned"),
                            ("rejected", "Rejected"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("payment_bank", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_fee",
                        to="admissions.application",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_school_fees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OLevelSubject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("english", "English Language"),
                            ("mathematics", "Mathematics"),
                            ("biology", "Biology"),
                            ("chemistry", "Chemistry"),
                            ("physics", "Physics"),
                            ("agriculture", "Agriculture"),
                            ("economics", "Economics"),
                            ("commerce", "Commerce"),
                            ("accounting", "Accounting"),
                            ("government", "Government"),
                            ("history", "History"),
                            ("geography", "Geography"),
                            ("civic_education", "Civic Education"),
                            ("literature", "Literature in English"),
                            ("hausa", "Hausa Language"),
                            ("yoruba", "Yoruba Language"),
                            ("igbo", "Igbo Language"),
                            ("french", "French"),
                            ("computer", "Computer Studies"),
                            ("islamic_studies", "Islamic Studies"),
                            ("christian_rel", "Christian Religious Studies"),
                            ("further_maths", "Further Mathematics"),
                            ("data_processing", "Data Processing"),
                            ("home_economics", "Home Economics"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("B2", "B2"),
                            ("B3", "B3"),
                            ("C4", "C4"),
                            ("C5", "C5"),
                            ("C6", "C6"),
                            ("D7", "D7"),
                            ("E8", "E8"),
                            ("F9", "F9"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="admissions.olevelresult",
                    ),
                ),
            ],
            options={
                "unique_together": {("result", "subject")},
            },
        ),
    ]
