# Generated by Django 5.1.3 on 2026-05-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_must_change_password_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("bursar", "Bursar"),
                    ("academic_officer", "Academic Officer"),
                    ("registrar", "Registrar"),
                    ("student", "Student"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
