# Generated by Django 5.2.13 on 2026-05-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("bursar", "Bursar"),
                    ("academic_officer", "Academic Secretary"),
                    ("registrar", "Registrar"),
                    ("lecturer", "Lecturer"),
                    ("student", "Student"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
