# Generated by Django 5.2.13 on 2026-05-06 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_alter_course_id_alter_department_id_and_more"),
        ("core", "0003_alter_semester_options_alter_session_options_and_more"),
        ("students", "0003_delete_courseregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("carryover", "Carry Over"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=2)),
                ("is_carryover", models.BooleanField(default=False)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="academics.course",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_registrations",
                        to="core.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_registrations",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "semester", "course")},
            },
        ),
        migrations.CreateModel(
            name="SemesterCourseStructure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("diploma1", "Diploma I"), ("diploma2", "Diploma II")],
                        max_length=10,
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True, related_name="structures", to="academics.course"
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_structures",
                        to="academics.programme",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_structures",
                        to="core.semester",
                    ),
                ),
            ],
            options={
                "unique_together": {("programme", "level", "semester")},
            },
        ),
    ]
