# Generated by Django 5.2.13 on 2026-05-08 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_courseregistration_semestercoursestructure"),
        ("core", "0003_alter_semester_options_alter_session_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseOutline",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Diploma I", "Diploma I"),
                            ("Diploma II", "Diploma II"),
                        ],
                        max_length=20,
                    ),
                ),
                ("min_units", models.PositiveIntegerField(default=15)),
                ("max_units", models.PositiveIntegerField(default=24)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("courses", models.ManyToManyField(blank=True, to="academics.course")),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outlines",
                        to="academics.programme",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outlines",
                        to="core.semester",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("programme", "level", "semester")},
            },
        ),
    ]
