# Generated by Django 5.2.13 on 2026-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecturers", "0002_question_choice_quiz_question_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="questions_to_attempt",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="If set, each student sees this many random questions from the bank. Blank = show all.",
                null=True,
            ),
        ),
    ]
