# Generated by Django 5.1.3 on 2026-05-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecturers", "0005_assignment_assignmentgroup_groupsubmission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="group_question",
            field=models.TextField(
                default="", help_text="Specific question for group part (10 marks)"
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="individual_question",
            field=models.TextField(
                default="", help_text="Specific question for individual part (10 marks)"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="description",
            field=models.TextField(
                blank=True, help_text="General instructions/context (optional)"
            ),
        ),
    ]
